name: 'Purge cache existing in jsDelivr Network'
author: 'PiQuark6046 and contributors'
description: 'Clone your npm package into jsDelivr Network to enhance transmission speed'

inputs:
  package:
    description: 'The package name to be purged'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install npm packages
      run: |
        npm i
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Run program
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PACKAGE: ${{ inputs.package }}
        CI_WORKSPACE_PATH: ${{ github.workspace }}
        CI_ACTION_PATH: ${{ github.action_path }}
      run: |
        npm run ci -- --gh-token "$GITHUB_TOKEN" --package "$PACKAGE" --ci-workspace-path "$CI_WORKSPACE_PATH" --ci-action-path "$CI_ACTION_PATH"
      shell: bash
      working-directory: ${{ github.action_path }}